name       : haskell-parallel
version    : 3.2.1.1
release    : 5
source     :
    - https://hackage.haskell.org/package/parallel-3.2.1.1/parallel-3.2.1.1.tar.gz : 323bb9bc9e36fb9bfb08e68a772411302b1599bfffbc6de20fa3437ce1473c17
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a library for parallel programming.
description: |
    This package provides a library for parallel programming.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
