name       : haskell-parallel
version    : 3.2.1.0
release    : 1
source     :
    - http://hackage.haskell.org/package/parallel-3.2.1.0/parallel-3.2.1.0.tar.gz : 4de3cdbb71dfd13cbb70a1dc1d1d5cf34fbe9828e05eb02b3dc658fdc2148526
license    : BSD-3-Clause
component  : programming
summary    : This package provides a library for parallel programming.
description: |
    This package provides a library for parallel programming.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 parallel-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/parallel-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/parallel-$version/*.a
