name       : haskell-parallel
version    : 3.2.2.0
release    : 6
source     :
    - https://hackage.haskell.org/package/parallel-3.2.2.0/parallel-3.2.2.0.tar.gz : 170453a71a2a8b31cca63125533f7771d7debeb639700bdabdd779c34d8a6ef6
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a library for parallel programming.
description: |
    This package provides a library for parallel programming.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
